// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybikjafjdgsvcdhrxiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliaWtqYWZqZGdzdmNkaHJ4aXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTExMDgsImV4cCI6MjA2OTk2NzEwOH0.XkcXisCpmTs3CmyGE07bMHZmVhaLQer_0zN5VryRw8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});